export const DEFAULT_ZOOM = 1.12;

export const RENDER_CONFIG = {
  COLORS: {
    RED_RAIL: "#FF0000",
    BLUE_RAIL: "#00AAFF",
    POST_BG: "#E2E2E2",
    BLACK: "#000000",
    DIM_LINE: "#856404",
    GRID: "#f0f0f0",
  },
  DIMS: {
    SPACING_MM: 99,
    RAIL_H_MM: 99,
    POST_W_MM: 88,
    POST_EXTRA_H_MM: 160,
    LUG_TYPE_5_OUTER: 260,
    LUG_TYPE_5_W: 715,
    LUG_TYPE_1_W: 200,
    CANVAS_W: 1800,
    CANVAS_H: 800,
    MARGIN_RATIO: 200,
  },
};

export const DEFAULT_PAN_X = (RENDER_CONFIG.DIMS.CANVAS_W / 2) * (1 - DEFAULT_ZOOM);
export const DEFAULT_PAN_Y = (RENDER_CONFIG.DIMS.CANVAS_H / 2) * (1 - DEFAULT_ZOOM);